### ISSUE TITLE
issue while copy item

### ISSUE THREAD

**Issue by danthespal** [xKynn/zana#22]
League: Expedition 3.15
Version: 3.15.3b

while trying to copy this item:
```
Item Class: Shields
Rarity: Rare
Gloom Refuge
Colossal Tower Shield
--------
Quality: +47% (augmented)
Chance to Block: 23%
Armour: 2590 (augmented)
--------
Requirements:
Level: 72
Str: 159
--------
Sockets: R-W-R 
--------
Item Level: 86
--------
+20 to maximum Life (implicit)
--------
+425 to Armour
98% increased Armour
+89 to maximum Life
21% chance to Avoid being Stunned
Recover 5% of Life when you Block
+23 to Intelligence (crafted)
+18% to Quality (crafted)
--------
Shaper Item
```

I got this error:

```
it  +425 to Armour
['+425 to Armour', '98% increased Armour', '+89 to maximum Life', '21% chance to Avoid being Stunned', 'Recover 5% of Life when you Block', '+23 to Intelligence (crafted)', '+18% to Quality (crafted)', '--------', 'Shaper Item']
['+425 to Armour', '98% increased Armour', '+89 to maximum Life', '21% chance to Avoid being Stunned', 'Recover 5% of Life when you Block', '+23 to Intelligence (crafted)', '+18% to Quality (crafted)']
File:Colossal Tower Shield inventory icon.png
+(10-20) to maximum [[Life]] +425 to Armour&lt;br&gt;98% increased Armour&lt;br&gt;+89 to maximum Life&lt;br&gt;21% chance to Avoid being Stunned&lt;br&gt;Recover 5% of Life when you Block&lt;br&gt;+23 to Intelligence (crafted)&lt;br&gt;+18% to Quality (crafted)
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Command.invoke() done, defined at /home/discord/bot/zana/lib/python3.9/site-packages/discord/ext/commands/core.py:854> exception=CommandInvokeError("Command raised an exception: ValueError: invalid literal for int() with base 10: 'lt;em class=&quot;tc '")>
Traceback (most recent call last):
  File "/home/discord/bot/zana/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/discord/bot/zana/cogs/poe.py", line 623, in convert
    await self.bot.loop.run_in_executor(None, utils._get_wiki_base, pob_item, d, self.client, "Chat Item")
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/discord/bot/zana/lib/python3.9/site-packages/poe/utils.py", line 1225, in _get_wiki_base
    modify_base_stats(wiki_base)
  File "/home/discord/bot/zana/lib/python3.9/site-packages/poe/utils.py", line 1070, in modify_base_stats
    arm = int(ensure_rangeless(item.armour))
ValueError: invalid literal for int() with base 10: 'lt;em class=&quot;tc '
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/home/discord/bot/zana/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/discord/bot/zana/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid literal for int() with base 10: 'lt;em class=&quot;tc '
```

**Comment by danthespal** [comment]
solved

**Comment by KongGal** [comment]
> solved

How did you end up solving this?

**Comment by danthespal** [comment]
I think I install PoE.py lib local, not sure, but this seems to be the error.
